// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balances.sql

package db

import (
	"context"
	"database/sql"
)

const getAllUsersCurrentBalances = `-- name: GetAllUsersCurrentBalances :many
SELECT
    id as user_id,
    name,
    COALESCE(balance, 0) as total_owed
FROM users
WHERE balance > 0
ORDER BY name
`

type GetAllUsersCurrentBalancesRow struct {
	UserID    int32          `json:"user_id"`
	Name      sql.NullString `json:"name"`
	TotalOwed string         `json:"total_owed"`
}

// Gets current balances for all users who owe money
func (q *Queries) GetAllUsersCurrentBalances(ctx context.Context) ([]GetAllUsersCurrentBalancesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersCurrentBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersCurrentBalancesRow
	for rows.Next() {
		var i GetAllUsersCurrentBalancesRow
		if err := rows.Scan(&i.UserID, &i.Name, &i.TotalOwed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentUserBalance = `-- name: GetCurrentUserBalance :one
SELECT
    id as user_id,
    COALESCE(balance, 0) as total_owed
FROM users
WHERE id = $1
`

type GetCurrentUserBalanceRow struct {
	UserID    int32  `json:"user_id"`
	TotalOwed string `json:"total_owed"`
}

// Gets the current balance for a user
func (q *Queries) GetCurrentUserBalance(ctx context.Context, id int32) (GetCurrentUserBalanceRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentUserBalance, id)
	var i GetCurrentUserBalanceRow
	err := row.Scan(&i.UserID, &i.TotalOwed)
	return i, err
}

const payOffUserBalance = `-- name: PayOffUserBalance :exec
UPDATE users
SET balance = 0.00
WHERE id = $1
`

// Marks user's balance as paid (sets to 0)
func (q *Queries) PayOffUserBalance(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, payOffUserBalance, id)
	return err
}

const payPartialUserBalance = `-- name: PayPartialUserBalance :exec
UPDATE users 
SET balance = CASE 
    WHEN balance <= $2 THEN 0.00
    ELSE balance - $2
END
WHERE id = $1
`

type PayPartialUserBalanceParams struct {
	ID      int32          `json:"id"`
	Balance sql.NullString `json:"balance"`
}

// Reduces user's balance by payment amount
func (q *Queries) PayPartialUserBalance(ctx context.Context, arg PayPartialUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, payPartialUserBalance, arg.ID, arg.Balance)
	return err
}

const updateUserBalance = `-- name: UpdateUserBalance :exec
UPDATE users 
SET balance = COALESCE(balance, 0) + $2
WHERE id = $1
`

type UpdateUserBalanceParams struct {
	ID      int32          `json:"id"`
	Balance sql.NullString `json:"balance"`
}

// Updates user's balance by adding an amount (for trip cost sharing)
func (q *Queries) UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserBalance, arg.ID, arg.Balance)
	return err
}
