// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Participants struct {
	ID          int32          `json:"id"`
	TripID      int32          `json:"trip_id"`
	UserID      int32          `json:"user_id"`
	ShareAmount sql.NullString `json:"share_amount"`
}

type Trips struct {
	ID        int32          `json:"id"`
	DriverID  int32          `json:"driver_id"`
	Date      sql.NullTime   `json:"date"`
	Time      sql.NullTime   `json:"time"`
	TotalCost sql.NullString `json:"total_cost"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Users struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Email     sql.NullString `json:"email"`
	Phone     sql.NullString `json:"phone"`
	Balance   sql.NullString `json:"balance"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
