// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package db

import (
	"context"
	"database/sql"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO participants (trip_id, user_id, share_amount)
VALUES ($1, $2, $3)
RETURNING id, trip_id, user_id, share_amount
`

type AddParticipantParams struct {
	TripID      int32          `json:"trip_id"`
	UserID      int32          `json:"user_id"`
	ShareAmount sql.NullString `json:"share_amount"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (Participants, error) {
	row := q.db.QueryRowContext(ctx, addParticipant, arg.TripID, arg.UserID, arg.ShareAmount)
	var i Participants
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.ShareAmount,
	)
	return i, err
}

const deleteParticipant = `-- name: DeleteParticipant :exec
DELETE FROM participants
WHERE id=$1
`

func (q *Queries) DeleteParticipant(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteParticipant, id)
	return err
}

const getParticipant = `-- name: GetParticipant :one
SELECT id, trip_id, user_id, share_amount FROM participants
WHERE id=$1
LIMIT 1
`

func (q *Queries) GetParticipant(ctx context.Context, id int32) (Participants, error) {
	row := q.db.QueryRowContext(ctx, getParticipant, id)
	var i Participants
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.ShareAmount,
	)
	return i, err
}

const listParticipantsByTrip = `-- name: ListParticipantsByTrip :many
SELECT id, trip_id, user_id, share_amount FROM participants
WHERE trip_id=$1
ORDER BY id
LIMIT $2 OFFSET $3
`

type ListParticipantsByTripParams struct {
	TripID int32 `json:"trip_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListParticipantsByTrip(ctx context.Context, arg ListParticipantsByTripParams) ([]Participants, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantsByTrip, arg.TripID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participants
	for rows.Next() {
		var i Participants
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.ShareAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipantShare = `-- name: UpdateParticipantShare :one
UPDATE participants
SET share_amount=$2
WHERE id=$1
RETURNING id, trip_id, user_id, share_amount
`

type UpdateParticipantShareParams struct {
	ID          int32          `json:"id"`
	ShareAmount sql.NullString `json:"share_amount"`
}

func (q *Queries) UpdateParticipantShare(ctx context.Context, arg UpdateParticipantShareParams) (Participants, error) {
	row := q.db.QueryRowContext(ctx, updateParticipantShare, arg.ID, arg.ShareAmount)
	var i Participants
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.ShareAmount,
	)
	return i, err
}
