// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trips.sql

package db

import (
	"context"
	"database/sql"
)

const createTrip = `-- name: CreateTrip :one
INSERT INTO trips (driver_id, date, time,total_cost)
VALUES ($1, $2, $3, $4)
RETURNING id, driver_id, date, time, total_cost, created_at
`

type CreateTripParams struct {
	DriverID  int32          `json:"driver_id"`
	Date      sql.NullTime   `json:"date"`
	Time      sql.NullTime   `json:"time"`
	TotalCost sql.NullString `json:"total_cost"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (Trips, error) {
	row := q.db.QueryRowContext(ctx, createTrip,
		arg.DriverID,
		arg.Date,
		arg.Time,
		arg.TotalCost,
	)
	var i Trips
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Date,
		&i.Time,
		&i.TotalCost,
		&i.CreatedAt,
	)
	return i, err
}

const createTripWithParticipantsAndBalances = `-- name: CreateTripWithParticipantsAndBalances :exec
BEGIN
`

// This should be executed within a transaction in your Go code
// Parameters: $1=driver_id, $2=date, $3=time, $4=total_cost, $5=participant_data (JSON or separate calls)
// Note: This is a template - actual implementation will require multiple queries in a transaction
func (q *Queries) CreateTripWithParticipantsAndBalances(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createTripWithParticipantsAndBalances)
	return err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM trips
WHERE id=$1
`

func (q *Queries) DeleteTrip(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteTrip, id)
	return err
}

const getTrip = `-- name: GetTrip :one
SELECT id, driver_id, date, time, total_cost, created_at FROM trips
WHERE id=$1
LIMIT 1
`

func (q *Queries) GetTrip(ctx context.Context, id int32) (Trips, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trips
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Date,
		&i.Time,
		&i.TotalCost,
		&i.CreatedAt,
	)
	return i, err
}

const getTripWithParticipants = `-- name: GetTripWithParticipants :many
SELECT
    t.id as trip_id,
    t.driver_id,
    t.date,
    t.time,
    t.total_cost,
    p.user_id as participant_id,
    p.share_amount,
    u.name as participant_name
FROM trips t
LEFT JOIN participants p ON t.id = p.trip_id
LEFT JOIN users u ON p.user_id = u.id
WHERE t.id = $1
`

type GetTripWithParticipantsRow struct {
	TripID          int32          `json:"trip_id"`
	DriverID        int32          `json:"driver_id"`
	Date            sql.NullTime   `json:"date"`
	Time            sql.NullTime   `json:"time"`
	TotalCost       sql.NullString `json:"total_cost"`
	ParticipantID   sql.NullInt32  `json:"participant_id"`
	ShareAmount     sql.NullString `json:"share_amount"`
	ParticipantName sql.NullString `json:"participant_name"`
}

func (q *Queries) GetTripWithParticipants(ctx context.Context, id int32) ([]GetTripWithParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTripWithParticipants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripWithParticipantsRow
	for rows.Next() {
		var i GetTripWithParticipantsRow
		if err := rows.Scan(
			&i.TripID,
			&i.DriverID,
			&i.Date,
			&i.Time,
			&i.TotalCost,
			&i.ParticipantID,
			&i.ShareAmount,
			&i.ParticipantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT id, driver_id, date, time, total_cost, created_at FROM trips
ORDER BY date DESC, time DESC
LIMIT $1 OFFSET $2
`

type ListTripsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTrips(ctx context.Context, arg ListTripsParams) ([]Trips, error) {
	rows, err := q.db.QueryContext(ctx, listTrips, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trips
	for rows.Next() {
		var i Trips
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.Date,
			&i.Time,
			&i.TotalCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTrip = `-- name: UpdateTrip :one
UPDATE trips
SET driver_id=$2, date=$3, time=$4,total_cost=$5
WHERE id=$1
RETURNING id, driver_id, date, time, total_cost, created_at
`

type UpdateTripParams struct {
	ID        int32          `json:"id"`
	DriverID  int32          `json:"driver_id"`
	Date      sql.NullTime   `json:"date"`
	Time      sql.NullTime   `json:"time"`
	TotalCost sql.NullString `json:"total_cost"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) (Trips, error) {
	row := q.db.QueryRowContext(ctx, updateTrip,
		arg.ID,
		arg.DriverID,
		arg.Date,
		arg.Time,
		arg.TotalCost,
	)
	var i Trips
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.Date,
		&i.Time,
		&i.TotalCost,
		&i.CreatedAt,
	)
	return i, err
}
